### ISSUE TITLE
DAO deployment console error

### ISSUE THREAD

**Issue by frozeman** [Ajand/DUP-contracts#1]
```js
Uncaught (in promise) Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.6.8)
    at ac.makeError (_app-37bff8e43df43f64.js:31:130515)
    at ac.throwError (_app-37bff8e43df43f64.js:31:130629)
    at _app-37bff8e43df43f64.js:31:260305
    at async Promise.all (/index 0)
index-2f7948e71505d8f0.js:1 Object
```

**Comment by aj-maz** [comment]
@frozeman Hello Fabian, could you please give me more context about when this is happening? Is the browser console error when you want to deploy a new DAO using the dao maker wizard form?
Deployment takes a bit of time since UP creation using lsp-factory is a bit slow, but now I think I can see your DAO here: https://www.dupdao.com/dao/4

**Comment by aj-maz** [comment]
@frozeman Oh, I checked again and find the solution: If it's the first time you are visiting the site you first need to click on the connect with UP, I was a bit short on time and did not manage to add a backup provider for the system.
